Extend badges in readme and add logo
4C-multiphysics/4C pull request #87
Opened 2024-11-29 16:58 UTC by davidrudlstorfer

## Description and Context

Added the current 4C logo as a replacement to the name 4C in the header

Also saved the static badges into assets and added them to the readme

## Related Issues and Merge Requests

#42

2024-11-29 16:58 UTC, davidrudlstorfer commented
![image](https://github.com/user-attachments/assets/b0b188b9-4c85-4dd9-977a-f7c30e511eaf)

2024-11-29 17:12 UTC, davidrudlstorfer commented
@amgebauer the github logo is still pulled from github within the SVG file for the badges - we could also remove the Github logo

2024-11-29 17:22 UTC, sebproell commented
> @amgebauer the github logo is still pulled from github within the SVG file for the badges - we could also remove the Github logo

I think we can just drop the logo here although I guess pulling from Github is OK since we are on Github anyway. The reason why I would drop it is that these badges are not really related to Github. We self-host the website and the docs are separate from the repo as well. Yes, we create them via actions, but the badge is not really about the development on Github which is the case for the workflow badges.

2024-11-29 17:27 UTC, davidrudlstorfer commented
> > @amgebauer the github logo is still pulled from github within the SVG file for the badges - we could also remove the Github logo
> 
> I think we can just drop the Github logo here although I guess pulling from Github is OK since we are on Github anyway. The reason why I would drop it is that these badges are not really related to Github. We self-host the website and the docs are separate from the repo as well. Yes, we create them via actions, but the badge is not really about the development on Github which is the case for the workflow badges.

Done ✅

2024-11-29 17:34 UTC, amgebauer commented on assets/logo/4c-logo.svg
I'm not sure whether we want to add this logo now. We never agreed on a logo yet. Maybe just leave the 4C title for now.

2024-11-29 17:40 UTC, davidrudlstorfer commented
@sebproell I've moved the `assets` into `utilities`

@amgebauer as discussed the logo is identical to the website, once a new logo is designed both need to be updated

2024-11-29 18:26 UTC, mayrmt commented
I appreciate the initiative, but there is no official logo yet, so please do not put one into the repository. Thanks!

2024-11-29 18:27 UTC, mayrmt requested changes
I appreciate the initiative, but there is no official logo yet, so please do not put one into the repository. Thanks!

(Yes, there's a logo on the website. In my opinion, it should not be there either.)

2024-12-01 15:00 UTC, davidrudlstorfer commented
@mayrmt thanks for your feedback 🙏🏻

I've removed the logo from the readme as well as from the utilities and adjusted the commit message accordingly.

To stay consistent between the Github repo and our website we should also remove the logo from the website ASAP and create an issue that we need a logo for the usage within the repo and on the website. Maybe someone can remove the logo from the website

Therefore, this MR would be ready for review again

2024-12-02 07:51 UTC, mayrmt approved these changes

2024-12-02 08:24 UTC, amgebauer approved these changes

2024-12-02 09:02 UTC, merged